services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codestruct
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/codestruct?schema=public
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 3000
      NODE_ENV: development
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_REDIRECT_URI: ${GITHUB_REDIRECT_URI}
      FRONTEND_ORIGIN: http://localhost:5173
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run start:dev"

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: http://backend:3000
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
